### ISSUE TITLE
Creating Databrick dashboard to keep track of DB usage

### ISSUE THREAD

**Issue by FrancoisWerbrouck-CFIA** [ai-cfia/nachet-datastore#10]
Our database is hosted by the Federal Science DataHub (FSDH). They offer an SQL editor service, but we aren't fan of it since we need to consistently copy the tables. We would like to have a script that would generate a view so we only need to copy the view's results to showcase in the Dashboard.

**Comment by Francois-Werbrouck** [comment]
This issue will be abandonned since the FSDH SQL editor doesn't work on the vpn/office and it can't be ause to manage and query the db easily.
