### ISSUE TITLE
Creating structure for Nachet DB packages

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/nachet-datastore#11]
We would like to create processes par with the Backend team. Therefore we need to build a module so the Backend team can easily manage the application and database without having to directly interact with the database.

- [x] Create Documentation for new processes
- [x] Update Schema: Indexes -> Sessions and adding SeedPicture relationship
- [x] Update Secret
- [x] Update import processes for new structure

**Comment by rngadam** [comment]
@Francois-Werbrouck checklist is completely done; can we add remainings tasks if any?
