### ISSUE TITLE
Create process to upload metadata for trusted users

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/nachet-datastore#13]
We want to create a process that will be used by the Backend Team. The process will upload a set of picture to the Nachet Database.

- [x] Create process template
- [x] Create builder PictureSet.json and Pictures.json
- [x] Inserts metadata into DB with relationships 
- [x] Building testing sequence for the db functions
- [x] Building test sequences for the metadata functions
- [x] Refactor the Structure of the repository and rename it
- [ ] Adding Blob storage responsibility
- [ ] Adapt the mass import process with new structure
- [ ] Create testing sequence for the adapted processes

**Comment by rngadam** [comment]
Part of the checklist should contain additional steps:

- [ ] user documentation
- [ ] tests by trusted user
