### ISSUE TITLE
Metadata Importation workflow

### ISSUE THREAD

**Issue by FrancoisWerbrouck-CFIA** [ai-cfia/nachet-datastore#2]
We need to create a workflow to enable the upload of the metadata to a new Database.

- [x] Create metadata structure
- [x] Create Database + scripts
- [x] Populate DB with default seeds
- [x] Populate DB with verified data
- [x] Adding Query module

**Comment by FrancoisWerbrouck-CFIA** [comment]
I created a markdown showcasing the process of a new User subscribing to his own storage space on Azure and the upload of files from the user.

TODO: Adding the processing of the files by the dev until the files/metadata is ready to use

**Comment by FrancoisWerbrouck-CFIA** [comment]
Edited Upload graph, Added Processing Graph, Added a Legend, Added an Observation section about the whole workflow

TODO: Adding an Idea section with points concerning how we could collect data for our upcoming DB

**Comment by rngadam** [comment]
@FrancoisWerbrouck-CFIA don't forget to set the Projects field in your issues
