### ISSUE TITLE
Setup a pyproject.toml to enable project packaging (pip)

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/nachet-datastore#20]
### Description 🚀 

Nachet datastore is meant to be a library use by Nachet Backend to send and retrieve data from the Nachet database (Blob Storage, PostgreSQL, etc.) As such the project will need a ` pyproject.toml` for `pip` to be able to import the project.

### Expected Behavior 📈

The project is importable by pip with a readable ` pyproject.toml`

### Current Behavior 📉

Without the ` pyproject.toml`, the project is not importable.

### Acceptance Criteria

- A ` pyproject.toml` is set up
- It follow [PEP518](https://peps.python.org/pep-0518/)

### Additional Context 📌

Here an example with ailab-db: [ailab-db pyproject.toml](https://github.com/ai-cfia/ailab-db/blob/main/pyproject.toml)

**Comment by Francois-Werbrouck** [comment]
This issue is waiting for review. It respects the acceptance criterias.
