### ISSUE TITLE
Implement batch import functions to upload pictures and picture set

### ISSUE THREAD

**Issue by sylvanie85** [ai-cfia/nachet-datastore#37]
## Context: 
This is related to [nachet-backend#74](https://github.com/ai-cfia/nachet-backend/issues/74) issue about the batch import of pictures where the BE needs to implement datastore functions to create picture set and upload picture in the database.

#### Sequence Diagrame of the batch import

```mermaid
sequenceDiagram;
   title: Batch Image Import 1.0.0
  autonumber
  actor User
  participant Frontend
  participant Backend
  participant Datastore

    User ->>+Frontend: Upload session request
    Frontend->>+Backend: HTTP Post Req.
    Backend->>+Datastore: get_all_seeds(cursor)
    Datastore-->>-Backend: seeds res.
    Backend-->>-Frontend: seeds res.
    Frontend -->>-User: Show session form
    User -) User: Fill form :<br> Seed selection, nb Seeds/Pic, Zoom
    User -)+Frontend: Upload: folder of pictures
    Frontend ->>+Backend: HTTP Post Req.
    Backend -)+ Datastore: create_picture_set (cursor, user_id, container_client, nb_pictures)
    Datastore --)- Backend : picture_set_id
    Backend -->>- Frontend : picture_set_id
    loop for each picture to upload
    Frontend ->>+Backend: HTTP Post Req. (with picture_set_id)
    Backend -)Datastore: upload_picture(cursor, container_client, encoded_picture, picture_set_id, **data)
    Note over Backend, Datastore: data contains at least the following <br>  value: seed_name, zoom_level, nb_seeds
    end
```

## Acceptance Criteria:

1. The BE can manually create a picture_set without uploading pictures
2. The BE can upload a picture to a specific picture_set

**Comment by Francois-Werbrouck** [comment]
> The BE can upload a picture to a specific picture_set

I recommend changing `upload_picture(cursor, user_id, picture_hash, container_client):` so it can take in a picture_set_id if given and upload the picture to said picture_set in the blob storage. 

I also think we need to specify our Error handling policy between layers for this issue and  [#74](https://github.com/ai-cfia/nachet-backend/issues/74)

I also think the user might be facing long upload time if we plan on uploading the pictures individually. We might have to explore avenues of uploading the pictures by small batch between the BE and Datastore depending on our testing.
