### ISSUE TITLE
Rework the delete of a folder to save for training

### ISSUE THREAD

**Issue by sylvanie85** [ai-cfia/nachet-datastore#63]
A user may want to delete a folder, but the images in that folder may be useful for training purposes. for example, if an image's inference is fully validated, or if it comes from a batch import.

This is why we want to be able to either :
- move validated images into a development container and delete others
- or, if the user wants, delete all images and related inferences permanently.

Tasks :
- [x] new function that search for validated pictures in a folder
- [x] modify existing delete function to delete all pictures permanently
- [x] new delete_with_archive function that move validated pictures in the dev container

**Comment by Francois-Werbrouck** [comment]
Dont forget to tag your projects 🫤
